### ISSUE TITLE
Provide the app to requests

### ISSUE THREAD

**Issue by flub** [florentx/fiole#1]
It is useful to have access to the application object in a view.  This can be done in two ways:
1. Putting the app in `environ`: `fiole.app`.  This is easily done in the `.handle_request()` method of `Fiole`.
2. Passing in the app when creating the Request instance.  This can again be easily done in the same place.

**Comment by florentx** [comment]
Thank you for the proposal. It will be added as `environ['fiole.app']` probably.

**Comment by flub** [comment]
Once the app is in the environ it is also possible to move the secret key
into the app instead off having it as a global. At least for the request.
For the response this may still need an api change in order to avoid a
global, but at least code having the request will have the app object with
the secret key accessible somehow.

**Comment by florentx** [comment]
This change was accepted and merged.
