### ISSUE TITLE
Provide Accept-style header parsing

### ISSUE THREAD

**Issue by flub** [florentx/fiole#2]
It would be nice if parsing of Accept HTTP headers is supported natively.  IMHO this is a pretty important function to have when building a REST-like API.  The best code I have found for this is from WebOb, and the class is very stand-alone (MIT licensed) so can be easily adopted.

**Comment by florentx** [comment]
thank you for the proposal.

I agree that a subset of `webob.acceptparse` could be merged into `fiole`. I'll take a look.

**Comment by florentx** [comment]
Feature merged in trunk.

Thanks

**Comment by flub** [comment]
Thanks!
