### ISSUE TITLE
Improve template location configuration

### ISSUE THREAD

**Issue by flub** [florentx/fiole#3]
Hi,

Currently you can customise `fiole.engine.loader.template_folder` but it is only ever valid as a relative directory to `fiole._get_root_folder()`.  Instead it would be nice if you could set it to any directory you like similar to how `fiole.static_folder` works.

To achieve this I created a subclass of Loader, which does way to much copy-pasting, but shows how I think this should be solved:

```
class Loader(fiole.Loader):
    """Subclass to control where templates are stored"""
    template_folder = os.path.join(fiole._get_root_folder(), 'templates')

    def load(self, name, source=None):
        """Return template by name."""
        if source is not None:
            return (name, unicode(source))
        if name in self.templates:
            return (name, self.templates[name])
        path = os.path.join(self.template_folder, name)
        with open(path, 'rb') as f:
            return (path, f.read().decode('utf-8'))
```

This allows you to re-assign `Loader.template_folder` to e.g. any absolute directory you like.

**Comment by florentx** [comment]
You can already assign an absolute path to `engine.loader.template_folder`, and it is used, because `os.path.join` allows this. No need to subclass.

However, I plan to review the `_get_root_folder` some day, because it seems it does not work in all cases. Maybe I will drop it.

Ideas and feedback are welcome.

**Comment by flub** [comment]
Ah, ok.  I should have just tried instead of reading the source.  OTOH now I know os.path resets when it has an absolute path.

Afraid I don't really know if there's a better way of handing _get_root_folder, I have to individually configure my paths which I get from the rest of the application.  As a quickly-get-started default `_get_root_folder()` seemed as good as any to me.  Perhaps support a way of setting a root folder on the `Fiole` instance?
