### ISSUE TITLE
Quick access to the absolute URL of a request

### ISSUE THREAD

**Issue by flub** [florentx/fiole#4]
When building an API I often need to construct the absolute URL of a resource and then construct new ones using `urlparse.urljoin()`.  Because of urljoin I need to be sure the URL ends in a trailing `/` as otherwise the results are very different.  Currently I do this as such:

```
url = wsgiref.utils.request_uri(request.environ, include_query=False)
if url[-1:] != b'/':
    url += b'/'
```

However I'm rather jealous of the `request.path` variable and was wondering if it was possible to add maybe `request.url` or `request.base_url` or something which is the correct absolute URL with a guaranteed trailing `/`?

**Comment by florentx** [comment]
This will be in the upcoming 0.4

http://fiole.readthedocs.org/en/latest/developer.html#changes
