### ISSUE TITLE
escape should be by default

### ISSUE THREAD

**Issue by xcombelle** [florentx/fiole#5]
If I read correctly the examples, the escape is not by default. I think it's too easy to forget to add |e once. better way would be to add |safe when needed.

**Comment by florentx** [comment]
actually, it's very easy to enable it globally:

``` python
>>> import fiole
>>> fiole.engine.default_filters = ['escape']
>>> 
>>> fiole.render_template(source='Hello {{party.capitalize()}}',
...                       party='<script src="evil" />')
u'Hello &lt;script src=&quot;evil&quot; /&gt;'
```

I should fix the documentation, because the sentence _"HTML escaping cannot be activated globally"_ is wrong. There's no such restriction.

Reference:
http://fiole.readthedocs.org/en/latest/api.html#fiole.Engine.default_filters

**Comment by florentx** [comment]
I've added the "skip default filters" special filter for the upcoming 0.4
The documentation is slightly improved too.
